FROM ruby:3.2.10
ENV RAILS_ENV=development

RUN apt-get update -qq \
  && apt-get install -y build-essential libpq-dev nodejs npm cron \
  && npm install -g yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app

COPY Gemfile* /app/
RUN bundle install
COPY . /app
